### ISSUE TITLE
Implement threaded or low-level interpreter

### ISSUE THREAD

**Issue by playXE** [jazz-lang/jlight#5]
Interpreter that just have big `switch..case` ( `match` in Rust) may be slow since it may not fit into CPU cache. To improve this we can implement:

1.Threaded interpreter: SImpliest solution since it doesn't require knowledge of assembly and writing big assembly files for each platform (will require some assembly to implement something like `goto` for threading, but it's much easier than ll-interpreter). Threaded interpreters usually much faster than just using `switch...case`.
2. Low-Level Interpreter: Low-level interpreter should be written in assembly, but it will give very big boost to performance since it will use real machine stack instead of "fake" stack that you allocate in heap for bytecode program.

**Comment by namibj** [comment]
> Interpreter that just have big `switch..case` ( `match` in Rust) may be slow since it may not fit into CPU cache. To improve this we can implement:
> 
> 1.Threaded interpreter: SImpliest solution since it doesn't require knowledge of assembly and writing big assembly files for each platform (will require some assembly to implement something like `goto` for threading, but it's much easier than ll-interpreter). Threaded interpreters usually much faster than just using `switch...case`.
Using functions that most/all cases are delegated to, combined with profiling to allow rustc/llvm to determine which functions should actually be inlined, and which shouldn't.
> 2. Low-Level Interpreter: Low-level interpreter should be written in assembly, but it will give very big boost to performance since it will use real machine stack instead of "fake" stack that you allocate in heap for bytecode program.
The downside is that a mixed stack has a tendency to cause stack corruption when invalid bytecode seqyences are encountered. I see a baseline JIT via Cranelift or even static opcode sequences (no compile(aka JIT)-time register allocation) as better than a tricky assembly interpreter.
Using a shared stack without basic checking by the JIT sounds like a security nightmare waiting to happen.
